const colors = {
  light: {
    text: "#1A0F0A",
    tint: "#8B3A2A",
    background: "#F9F6EE",
    foreground: "#1A0F0A",
    card: "#FFFDF5",
    cardForeground: "#1A0F0A",
    primary: "#8B3A2A",
    primaryForeground: "#FFFFFF",
    secondary: "#EDE6D6",
    secondaryForeground: "#3D2B1F",
    muted: "#E8E0CF",
    mutedForeground: "#7A6E5F",
    accent: "#C17D3C",
    accentForeground: "#FFFFFF",
    destructive: "#D32F2F",
    destructiveForeground: "#FFFFFF",
    border: "#D9CDB8",
    input: "#D9CDB8",
  },
  dark: {
    text: "#F0EAD6",
    tint: "#C17D3C",
    background: "#0E0C09",
    foreground: "#F0EAD6",
    card: "#1A1510",
    cardForeground: "#F0EAD6",
    primary: "#C17D3C",
    primaryForeground: "#0E0C09",
    secondary: "#221C14",
    secondaryForeground: "#D4C9A8",
    muted: "#221C14",
    mutedForeground: "#8A7E6A",
    accent: "#C17D3C",
    accentForeground: "#0E0C09",
    destructive: "#EF5350",
    destructiveForeground: "#FFFFFF",
    border: "#2A2218",
    input: "#2A2218",
  },
  radius: 10,
};

export default colors;
